
replicaCount: 1
deploymentName: auth
image:
  repository: "192.168.236.156:8083/auth2-backend"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "production-0434273e"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: auth
  type: ClusterIP
  port: 80
  targetPort: 80



ingress:
  enabled: false
  hostname: auth.axoex.ir
  className: traefik
  annotations: {}
  paths:
    - path: /
      pathType: Prefix
      service:
        port: 80


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


# affinity: {}
secretName: auth-secrets
environmentVariables:
  - name: DB_MSSQL_SERVER
    key: DB_MSSQL_SERVER
  - name: DB_MSSQL_USER
    key: DB_MSSQL_USER
  - name: DB_MSSQL_PASS
    key: DB_MSSQL_PASS
  - name: DB_MSSQL_PORT
    key: DB_MSSQL_PORT
  - name: DB_MSSQL_DB_auth
    key: DB_MSSQL_DB_auth
  - name: JWT_REFRESH_SECRET
    key: JWT_REFRESH_SECRET
  - name: JWT_SECRET
    key: JWT_SECRET
  - name: MONGO_CONNECTION_STRING
    key: MONGO_CONNECTION_STRING
  - name: PORT
    key: PORT
  - name: PRODUCT_MODE
    key: PRODUCT_MODE
  - name: RAHYAB_FROM
    key: RAHYAB_FROM
  - name: RAHYAB_PASSWORD
    key: RAHYAB_PASSWORD
  - name: RAHYAB_USERNAME
    key: RAHYAB_USERNAME
  - name: RBMQ_QUEUE
    key: RBMQ_QUEUE
  - name: RBMQ_URL
    key: RBMQ_URL
  - name: REDIS_CONNECTION_STRING
    key: REDIS_CONNECTION_STRING
  - name: SENTRY_DNS
    key: SENTRY_DNS

