
replicaCount: 1

image:
  repository: "192.168.236.156:8083/exchange-backend"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "production-380868f5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 80



ingress:
  enabled: false
  hostname: bsaraf.axoex.ir
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  paths:
    - path: /
      pathType: Prefix
      service:
        port: 80


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


# affinity: {}
secretName: saraf-secrets
environmentVariables:
  - name: PORT
    key: PORT
  - name: ADMIN_NID
    key: ADMIN_NID
  - name: ADMIN_BIRTHDATE
    key: ADMIN_BIRTHDATE
  - name: ADMIN_MOBILE
    key: ADMIN_MOBILE
  - name: ADMIN_PASS
    key: ADMIN_PASS
  - name: BASE_URL
    key: BASE_URL
  - name: AUTH_URL
    key: AUTH_URL
  - name: BHUB_URL
    key: BHUB_URL
  - name: DB_HOST_REDIS
    key: DB_HOST_REDIS
  - name: HUB_URL
    key: HUB_URL
  - name: HUB_APP_NAME
    key: HUB_APP_NAME
  - name: HUB_USER_NAME
    key: HUB_USER_NAME
  - name: HUB_PASSWORD
    key: HUB_PASSWORD
  - name: MICRO_URL
    key: MICRO_URL
  - name: MICRO_APP_NAME
    key: MICRO_APP_NAME
  - name: MICRO_REFRESH_TOKEN
    key: MICRO_REFRESH_TOKEN
  - name: HUB_REFRESH_TOKEN
    key: HUB_REFRESH_TOKEN
  - name: RBMQ_QUEUE
    key: RBMQ_QUEUE
  - name: RBMQ_URL
    key: RBMQ_URL
  - name: RBMQ_PORT
    key: RBMQ_PORT
  - name: SQL_DB_IP
    key: SQL_DB_IP
  - name: WALLET_URL
    key: WALLET_URL
  - name: ELASTIC_API_URL
    key: ELASTIC_API_URL
  - name: PROJECT_NAME
    key: PROJECT_NAME
  - name: SQL_DB_PASSWORD
    key: SQL_DB_PASSWORD
  - name: SQL_DB_USER
    key: SQL_DB_USER
#  - name: SENTRY_DSN
#    key: SENTRY_DSN

